/* empty css                      */import{S as w,N as g,P as h}from"./assets/vendor-B-mvldNl.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function u(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=u(e);fetch(e.href,t)}})();let f=null,p=null,m=null;const y=()=>{window.innerWidth<1440?(f||(f=new w(".three-swiper",{modules:[g,h],slidesPerView:1,spaceBetween:16,navigation:{nextEl:".three-next",prevEl:".three-prev"},pagination:{el:".three-pagination",clickable:!0,renderBullet:(c,r)=>`<span class="${r}"></span>`}})),p||(p=new w(".core-swiper",{modules:[g,h],slidesPerView:1,navigation:{nextEl:".core-next",prevEl:".core-prev"},pagination:{el:".core-pagination",clickable:!0}})),m||(m=new w(".play-swiper",{modules:[g,h],slidesPerView:1,navigation:{nextEl:".play-next",prevEl:".play-prev"},pagination:{el:".play-pagination",clickable:!0}}))):L()},L=()=>{f&&(f.destroy(!0,!0),f=null),p&&(p.destroy(!0,!0),p=null),m&&(m.destroy(!0,!0),m=null)};window.addEventListener("load",y);window.addEventListener("resize",y);document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),r=c.querySelector(".icon"),u=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const l=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 5H20M4 12H20M4 19H20" stroke="#171717" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,n=`
<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M30 30L6 6M30 6L6 30" stroke="#151515" stroke-width="2" stroke-linecap="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,r.innerHTML=t?n:l,t?o():i()}),a.forEach(d=>d.addEventListener("click",()=>{i(),r.innerHTML=l,t=!1})),window.addEventListener("scroll",s);function o(){u.style.display="block"}function i(){u.style.display="none"}function s(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function r(n){const o=document.getElementById(n);if(!o)return;const i=c(),s=o.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:s,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(o){const i=this.getAttribute("href");if(!i)return;const[s,d]=i.split("#");if(!d)return;const v=window.location.pathname.split("/").pop();!(s===""||s==="./"||s===v||s==="./"+v)||!document.getElementById(d)||(o.preventDefault(),r(d),t(d))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(i=>i.classList.remove("active"));const o=document.querySelector(`.navigation-item a[href*="#${n}"]`);o&&o.closest(".navigation-item").classList.add("active")}function l(){const n=window.pageYOffset+c()+100;a.forEach(o=>{const i=o.offsetTop,s=i+o.offsetHeight;n>=i&&n<s&&t(o.id)})}if(window.addEventListener("scroll",l),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{r(n),t(n)},300)}});
//# sourceMappingURL=index.js.map
